/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { Mesh, MeshStandardMaterial } from 'three'
import { GLTF } from 'three-stdlib'
import { ProductConfig } from '../ProductConfigurator';

interface ProductModelProps {
  config: ProductConfig;
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_Material_0002: Mesh
    Cylinder_Material_0002_1: Mesh
    Cylinder_Material_0002_2: Mesh
    Cylinder_Material_0002_3: Mesh
  }
  materials: {
    frame_material: MeshStandardMaterial
    leg_material: MeshStandardMaterial
    cushion_material: MeshStandardMaterial
    pillow_material: MeshStandardMaterial
  }
}

export function Model({ config, ...props }: ProductModelProps & JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/corner_sofa_base.glb') as GLTFResult

  const textures = useTexture({
    leatherDiffuse: '/textures/leather/diffuse.png',
    leatherNormal: '/textures/leather/normal.png',
    leatherRoughness: '/textures/leather/roughness.png',
    fabricDiffuse: '/textures/fabric/diffuse.png',
    fabricNormal: '/textures/fabric/normal.png',
    fabricRoughness: '/textures/fabric/roughness.png',
    denimDiffuse: '/textures/denim/diffuse.png',
    denimNormal: '/textures/denim/normal.png',
    woodDiffuse: '/textures/wood/diffuse.png',
    woodNormal: '/textures/wood/normal.png'
  });

  const customMaterials = useMemo(() => {
    const getMaterialProps = (materialType: string) => {
      const materialMap = {
        wood: { map: textures.woodDiffuse, normalMap: textures.woodNormal, roughness: 0.6, metalness: 0.0 },
        metal: { roughness: 0.1, metalness: 0.8 },
        plastic: { roughness: 0.3, metalness: 0.0 },
        leather: { map: textures.leatherDiffuse, normalMap: textures.leatherNormal, roughnessMap: textures.leatherRoughness, metalness: 0.1 },
        fabric: { map: textures.fabricDiffuse, normalMap: textures.fabricNormal, roughnessMap: textures.fabricRoughness, metalness: 0.0 },
        denim: { map: textures.denimDiffuse, normalMap: textures.denimNormal, roughness: 0.9, metalness: 0.0 },
        microfiber: { roughness: 0.7, metalness: 0.0 },
        linen: { roughness: 0.8, metalness: 0.0 }
      };
      return materialMap[materialType as keyof typeof materialMap] || { roughness: 0.5, metalness: 0.0 };
    };

    const frameMat = materials.frame_material.clone();
    const legMat = materials.leg_material.clone();
    const cushionMat = materials.cushion_material.clone();
    const pillowMat = materials.pillow_material.clone();

    Object.assign(frameMat, getMaterialProps(config.frameMaterial));
    Object.assign(cushionMat, getMaterialProps(config.cushionMaterial));
    Object.assign(pillowMat, getMaterialProps(config.pillowMaterial));
    
    // Scale textures
    [frameMat, cushionMat, pillowMat].forEach(mat => {
      if (mat.map) {
        mat.map.repeat.set(4, 4);
        mat.map.wrapS = mat.map.wrapT = 1000; // RepeatWrapping
      }
      if (mat.normalMap) {
        mat.normalMap.repeat.set(4, 4);
        mat.normalMap.wrapS = mat.normalMap.wrapT = 1000;
      }
      if (mat.roughnessMap) {
        mat.roughnessMap.repeat.set(4, 4);
        mat.roughnessMap.wrapS = mat.roughnessMap.wrapT = 1000;
      }
    });

    return { frame: frameMat, leg: legMat, cushion: cushionMat, pillow: pillowMat };
  }, [config.frameMaterial, config.cushionMaterial, config.pillowMaterial, materials, textures]);

  // Apply colors to materials
  customMaterials.frame.color.set(config.frameColor);
  customMaterials.cushion.color.set(config.cushionColor);
  customMaterials.pillow.color.set(config.pillowsColor);

  return (
    <group {...props} dispose={null}>
      <group position={[0.3, -1.3, 0.3]} rotation={[-Math.PI / 2, 0, 0]} scale={0.062}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material_0002.geometry}
          material={customMaterials.frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material_0002_1.geometry}
          material={customMaterials.leg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material_0002_2.geometry}
          material={customMaterials.cushion}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material_0002_3.geometry}
          material={customMaterials.pillow}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/corner_sofa_base.glb')
